create database assalaIskane;
use assalaIskane;
create table user(id varchar(10) primary key, nom varchar(20), prenom varchar(20), fonction varchar(30), numero varchar(15));
create table ouvrier(id varchar(15) primary key, nom varchar(20), prenom varchar(20), numero varchar(15));
create table projet(id varchar(40) primary key, nom varchar(40), id_resp varchar(10));
alter table projet add constraint foreign key (id_resp) references user(id);
create table chantier(id int primary key auto_increment, id_projet varchar(40), id_resp varchar(10));
alter table chantier add constraint foreign key (id_projet) references projet(id);
alter table chantier add constraint foreign key (id_resp) references user(id);
create table besoin(id int primary key auto_increment, nom varchar(20), date_demande date, qte int, validé_par varchar(10), id_chantier int);
alter table besoin add constraint foreign key (id_chantier) references chantier(id);
create table fichier_projet(id int primary key auto_increment, fichier blob, id_projet varchar(40));
alter table fichier_projet add constraint foreign key (id_projet) references projet(id);
create table absence(id int primary key auto_increment, id_ouvrier varchar(10), date_absence date, id_chantier int, absent int);
alter table absence add constraint foreign key (id_ouvrier) references ouvrier(id);
alter table absence add constraint foreign key (id_chantier) references chantier(id);
create table stock(id int primary key auto_increment, gerant varchar(50), numero varchar(15), email varchar(30));
create table materiel(id int primary key auto_increment, nom varchar(20), qte int, prix float, id_stock int);
alter table materiel add constraint foreign key (id_stock) references stock(id);
create table materiel_chantier(id_materiel int, id_chantier int, qte int);
alter table materiel_chantier add constraint foreign key (id_materiel) references materiel(id);
alter table materiel_chantier add constraint foreign key (id_chantier) references chantier(id);
create table materiaux(id int primary key auto_increment, nom varchar(50), type varchar(20), qte int, prix float, id_stock int);
alter table materiaux add constraint foreign key (id_stock) references stock(id);
create table materiaux_chantier(id_materiaux int, id_chantier int, qte int);
alter table materiaux_chantier add constraint foreign key (id_materiaux) references materiaux(id);
alter table materiaux_chantier add constraint foreign key (id_chantier) references chantier(id);