version: '3.8'

services:
  frontend:
    build: ./FrontEnd/front_v2
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080/assalaiskane/  # For API calls to backend

  backend:
    build: ./BackEnd/ASSALA_ISKANE_SpringBoot_BackEnd
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/assala_iskane_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: assalaIskane
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql  # Initialize DB
    ports:
      - "3306:3306"

volumes:
  mysql-data: